/*! (C) Ionic https://ionicframework.com - Mit License */
(function(u){"use-strict";function q(a){return void 0!==a&&null!==a}function J(a){return"string"===typeof a||"number"===typeof a}function Y(a){return a.replace(/-([a-z])/g,function(a){return a[1].toUpperCase()})}function Z(a){return a.replace(/([A-Z])/g,function(a){return"-"+a[0].toLowerCase()})}function O(){}function aa(a,b){if("child"===b)return a.firstElementChild;if("parent"===b){if(a.parentElement)return a.parentElement;if(a.parentNode&&a.parentNode.host)return a.parentNode.host}return"body"===b?a.ownerDocument.body:
"document"===b?a.ownerDocument:"window"===b?a.ownerDocument.defaultView:a}function ba(a){return"enter"===a?13:"escape"===a?27:"space"===a?32:"tab"===a?9:null}function K(a,b,c,d,f){return{c:a,b:b,j:c,f:d,a:f,s:void 0===b?void 0:b.key}}function P(a,b,c){a.Z="http://www.w3.org/2000/svg";if("foreignObject"!==c&&void 0!==b)for(a=0;a<b.length;++a)c=b[a].b,void 0!==c&&P(c,b[a].j,b[a].c)}function ca(a,b,c){var d={},f,e,g=void 0;a.nodeType&&(g=a);void 0!==c?(d=b,c&&c.constructor===Array?f=c:J(c)?e=c:c&&c.c&&
(f=[c])):void 0!==b&&(b&&b.constructor===Array?f=b:J(b)?e=b:b&&b.c?f=[b]:d=b);if(f&&f.constructor===Array)for(b=0;b<f.length;++b)J(f[b])&&(f[b]=K(void 0,void 0,void 0,f[b]));"s"!==a[0]||"v"!==a[1]||"g"!==a[2]||3!==a.length&&"."!==a[3]&&"#"!==a[3]||P(d,f,a);return K(a,d,f,e,g)}function da(a,b,c,d){if(a&&a.$meta){var f=a.$meta.listeners;if(f)for(var e=a.i=a.i||{},g=Object.keys(f),h=0;h<g.length;h++){var m=g[h],k=f[m];if(k.C===b){c&&!e[b]?e[b]=Q(a.$el,d?d+":"+b:b,a[m].bind(a),k):!c&&e[b]&&(e[b](),delete a.i[b]);
break}}}}function Q(a,b,c,d){if(!a)return O;null===L&&(L=ea(a));var f=L?{capture:!!d.capture,passive:!!d.passive}:!!d.capture;d=b.split(":");1<d.length&&(a=aa(a,d[0]),b=d[1]);d=b.split(".");if(1<d.length){b=d[0];var e=ba(d[1]);if(null!==e){var g=c;c=function(a){a.keyCode===e&&g(a)}}}a.addEventListener(b,c,f);return function(){a&&a.removeEventListener(b,c,f)}}function ea(a){var b=!1;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0}});a.addEventListener("test",null,c)}catch(d){}return b}
function fa(a,b){var c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},d=c["class"]=c["class"]||{},f=a.mode,e=a.color;d[b]=!0;f&&(d[b+"-"+f]=!0,e&&(d[b+"-"+e]=d[b+"-"+f+"-"+e]=!0));return c}function ga(a,b,c,d){if("function"!==typeof a.CustomEvent){var f=function(a,b){b=b||{bubbles:!1,cancelable:!1,detail:void 0};var e=document.createEvent("CustomEvent");e.initCustomEvent(a,b.bubbles,b.cancelable,b.detail);return e};f.prototype=a.Event.prototype;a.CustomEvent=f}return{theme:fa,emit:function(e,
c){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};void 0===d.composed&&(d.composed=!0);b&&(c=b(c));e&&e.$el&&e.$el.dispatchEvent(new a.CustomEvent(c,d))},listener:{enable:da},controllers:{},dom:d,config:c}}function R(a){switch(a){case "0":return"default";case "1":return"ios";case "2":return"md";case "3":return"wp"}return a}function ha(a,b,c,d,f,e,g,h){var m={};Object.keys(g).forEach(function(k){function w(){return m[k]}function p(e){m[k]!==e&&(m[k]=e,n&&n(e),S(a,b,c,d,f))}var n=h[k]?
e[h[k].W].bind(e):null;m[k]=ia(b,d,e,g[k].type,k);Object.defineProperty(d,k,{configurable:!0,get:w,set:p});Object.defineProperty(e,k,{configurable:!0,get:w,set:p})})}function ia(a,b,c,d,f){return void 0!==b[f]?b[f]:void 0!==c[f]?c[f]:0===d?a.getBoolean(f):1===d?a.getNumber(f):a.get(f)}function S(a,b,c,d,f){d.J||(d.J=!0,a.nextTick(function(){var e=a.X(f),g=!1,h=d.v;h||(h=d.v=new e.V,h.$el=d,h.$meta=e,ha(a,b,c,d,f,h,e.props,e.M),a.N(d,e,h),g=!0);if(e.D){var m=h,k=h.m?h.m:d,w=h.A,p=h.render&&h.render();
p&&(p.a=w,delete p.c);m.m=c(k,p)}else g&&h.render&&(m=h.render(),m.a=d,c(d,m,!0));if(g){e=e.listeners;g=h;m=Object.keys(e);for(k=0;k<m.length;k++)w=m[k],p=e[w],!1!==p.enabled&&(g.i=g.i||{},g.i[p.C]=Q(g.$el,p.C,g[w].bind(g),p));h.ionViewDidLoad&&h.ionViewDidLoad()}d.J=!1}))}function ja(a,b,c,d,f){a.nextTick(function(){var e=f.tag,g=f.l[ka(a,b,d)];g||(g=f.l.default);a.Y(g.U,f.$,function(){S(a,b,c,d,e)})})}function ka(a,b,c){var d=c.mode;if(q(d))return d;d=a.S(c,"mode");return q(d)?d:b.get("mode","md")}
function T(a,b){var c,d,f=b.a;a=a.b.attrs;var e=b.b.attrs;if((a||e)&&a!==e){a=a||{};e=e||{};for(c in e)b=e[c],d=a[c],d!==b&&(U[c]?b?f.setAttribute(c,""):f.removeAttribute(c):120!==c.charCodeAt(0)?f.setAttribute(c,b):58===c.charCodeAt(3)?f.setAttributeNS("http://www.w3.org/XML/1998/namespace",c,b):58===c.charCodeAt(5)?f.setAttributeNS("http://www.w3.org/1999/xlink",c,b):f.setAttribute(c,b));for(c in a)c in e||f.removeAttribute(c)}}function V(a,b){var c,d=b.a;a=a.b["class"];var f=b.b["class"];if((a||
f)&&a!==f){a=a||{};f=f||{};for(c in a)f[c]||d.classList.remove(c);for(c in f)if(b=f[c],b!==a[c])d.classList[b?"add":"remove"](c)}}function W(a,b,c){if("function"===typeof a)a.call(b,c,b);else if("object"===typeof a)if("function"===typeof a[0])if(2===a.length)a[0].call(b,a[1],c,b);else{var d=a.slice(1);d.push(c);d.push(b);a[0].apply(b,d)}else for(b=0;b<a.length;b++)W(a[b])}function la(){return function b(c){var d=b.ba,f=c.type,e=d.b.on;e&&e[f]&&W(e[f],d,c)}}function M(a,b){var c=a.b.on,d=a.listener,
f=a.a,e=b&&b.b.on,g=b&&b.a,h;if(c!==e){if(c&&d)if(e)for(h in c)e[h]||f.removeEventListener(h,d,!1);else for(h in c)f.removeEventListener(h,d,!1);if(e)if(a=b.listener=a.listener||la(),a.ba=b,c)for(h in e)c[h]||g.addEventListener(h,a,!1);else for(h in e)g.addEventListener(h,a,!1)}}function X(a,b){var c,d,f=b.a;a=a.b.props;var e=b.b.props;if((a||e)&&a!==e){a=a||{};e=e||{};for(c in a)e[c]||delete f[c];for(c in e)b=e[c],d=a[c],d===b||"value"===c&&f[c]===b||(f[c]=b)}}function H(a,b){return a.s===b.s&&a.c===
b.c}function N(a){var b,c;if(void 0!==a.b&&(M(a),void 0!==a.j))for(c=0;c<a.j.length;++c)b=a.j[c],null==b||"string"===typeof b||N(b)}function C(a,b,c,d,f){var e;e="ionicplatform".replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");if(a=(a=(new RegExp("[\\?&]"+e+"=([^&#]*)")).exec(a))?decodeURIComponent(a[1].replace(/\+/g," ")):null)return a===c;b=b.toLowerCase();for(c=0;c<d.length;c++)if(-1<b.indexOf(d[c])){for(d=0;d<f.length;d++)if(-1<b.indexOf(f[d]))return!1;return!0}return!1}for(var L=null,t="allowfullscreen async autofocus autoplay checked controls disabled draggable enabled formnovalidate hidden multiple noresize readonly required selected spellcheck".split(" "),
U=Object.create(null),x=0,ma=t.length;x<ma;x++)U[t[x]]=!0;var I=K("",{},[],void 0,void 0),t=u.Ionic=u.Ionic||{};t.DomCtrl=function(a){function b(){f=!0;a.requestAnimationFrame(function(a){var e,h,m;try{for(e=performance.now();h=c.shift();)h(a);for(;(h=d.shift())&&!(h(a),8<performance.now()-e););}catch(k){m=k}f=!1;(c.length||d.length)&&b();if(m)throw m;})}var c=[],d=[],f=!1;return{read:function(a){c.push(a);f||b()},write:function(a){d.push(a);f||b()},raf:a.requestAnimationFrame.bind(a)}}(u);t.NextTickCtrl=
function(a){function b(){d=!1;for(var a=c.slice(0),b=c.length=0;b<a.length;b++)a[b]()}var c=[],d=!1,f=void 0,e=/iphone|ipad|ipod|ios/.test(a.navigator.userAgent.toLowerCase());if("undefined"!==typeof Promise&&-1!==Promise.toString().indexOf("[native code]"))var g=Promise.resolve(),h=function(a){console.error(a)},f=function(){g.then(b).catch(h);e&&setTimeout(O)};else f=function(){setTimeout(b,0)};return{nextTick:function(a){c.push(a);d||(d=!0,f())}}}(u);t.ConfigCtrl=function(a,b){function c(c){var d=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:null;if(void 0!==a[c])return a[c];for(var e,g=0;g<b.length;g++)if((e=b[g].settings)&&void 0!==e[c])return e[c];return d}a=a||{};return{get:c,getBoolean:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,e=c(a);return null===e?b:"string"===typeof e?"true"===e:!!e},getNumber:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:NaN,e=parseFloat(c(a));return isNaN(e)?b:e}}}(t.config,function(a,b,c,d){var f=
c.filter(function(e){return e.isMatch&&e.isMatch(a,b)});f.length||(f=c.filter(function(a){return a.name===d}));return f}(u.location.href,u.navigator.userAgent,[{name:"ipad",settings:{keyboardHeight:500},isMatch:function(a,b){return C(a,b,"ipad",["ipad"],["windows phone"])}},{name:"iphone",isMatch:function(a,b){return C(a,b,"iphone",["iphone"],["windows phone"])}},{name:"ios",settings:{autoFocusAssist:"delay",hoverCSS:!1,inputBlurring:!0,inputCloning:!0,keyboardHeight:300,mode:"ios",scrollAssist:!0,
statusbarPadding:!1,swipeBackEnabled:!0,tapPolyfill:!1,virtualScrollEventAssist:!1,disableScrollAssist:!0},isMatch:function(a,b){return C(a,b,"ios",["iphone","ipad","ipod"],["windows phone"])}},{name:"android",settings:{activator:"ripple",autoFocusAssist:"immediate",inputCloning:!0,scrollAssist:!0,hoverCSS:!1,keyboardHeight:300,mode:"md"},isMatch:function(a,b){return C(a,b,"android",["android","silk"],["windows phone"])}},{name:"windows",settings:{mode:"wp",autoFocusAssist:"immediate",hoverCSS:!1},
isMatch:function(a,b){return C(a,b,"windows",["windows phone"],[])}},{name:"core",settings:{mode:"md",keyboardHeight:290}}],"core"));x=function(a,b,c,d){function f(a){function c(){clearTimeout(f);d.onerror=d.onload=null;d.parentNode.removeChild(d);delete k[a]}var d=e("script");d.charset="utf-8";d.async=!0;d.src=a;var f=setTimeout(c,12E4);d.onerror=d.onload=c;b.head.appendChild(d)}function e(a){return b.createElement(a)}var g={},h={},m={},k={},w={},p=!(a.ShadyDOM&&a.ShadyDOM.inUse),n=ga(a,c.eventNameFn,
c.ConfigCtrl,c.DomCtrl);c.loadComponents=function(a,b){var e=arguments;b(w,ca,n);for(var c=2;c<e.length;c++){var d,f=w,l=e[c],k,r=g[l[0]];r.listeners={};for(k=0;k<l[2].length;k++)d=l[2][k],r.listeners[d[0]]={C:d[1],capture:!!d[2],passive:!!d[3],enabled:!!d[4]};r.M={};for(k=0;k<l[3].length;k++)d=l[3][k],r.M[d[0]]={W:d[1]};r.D=!!l[4];"string"===typeof l[6]&&(k=r.l[R(l[5].toString())])&&(k.L=l[6]);r.V=f[l[1]];if(f=m[a]){l=0;for(r=f.length;l<r;l++)f[l]();delete m[a]}h[a]=!0}};return{aa:function(a,b){var e=
b[0],c=b[1],d={color:{},mode:{}};if(c)for(var f=0;f<c.length;f++)d[c[f][0]]={type:c[f][1]};a=g[a]={tag:a,l:{},props:d,K:[]};0===b[2]&&(a.$="low");b=Object.keys(e);for(c=0;c<b.length;c++)a.l[R(b[c].toString())]={U:e[b[c]]};b=Object.keys(a.props);for(c=0;c<b.length;c++)a.K.push(Z(b[c]));return a},X:function(a){return g[a]},Y:function(b,e,d){if(h[b])d();else{m[b]?m[b].push(d):m[b]=[d];var l=c.staticDir+"bundles/ionic."+b+".js";k[l]||(k[l]=!0,"low"===e?"requestIdleCallback"in a?a.requestIdleCallback(function(){f(l)},
{timeout:2E3}):setTimeout(function(){f(l)},600):f(l))}},ga:function(a){return 1===a.nodeType},ha:function(a){return 3===a.nodeType},fa:function(a){return 8===a.nodeType},nextTick:d.nextTick.bind(d),P:e,R:function(a,e){return b.createElementNS(a,e)},G:function(a){return b.createTextNode(a)},O:function(a){return b.createComment(a)},g:function(a,b,e){a.insertBefore(b,e)},w:function(a,b){a.removeChild(b)},u:function(a,b){a.appendChild(b)},I:function(a){return a.parentNode},H:function(a){return a.nextSibling},
T:function(a){return(a.tagName||"").toLowerCase()},B:function(a,b){a.textContent=b},ca:function(a){return a.textContent},S:function(a,b){return a.getAttribute(b)},N:function(a,c,d){c.D&&(d.A=a.attachShadow({mode:"open"}));var f=c.l[d.mode]||c.l.default;if(f&&f.L){var k=f.L;if(c.D&&p)f.F||(f.F=e("style"),f.F.innerHTML=k),d.A.appendChild(f.F.cloneNode(!0));else{c=c.tag+"."+d.mode;k=k.replace(/\:host\-context\((.*?)\)|:host\((.*?)\)|\:host/g,"__h");d=a;for(a=b.head;d=d.parentNode;)if(d.host&&d.host.shadowRoot){a=
d.host.shadowRoot;a.h=a.h||{};a.h[c]||(a.h[c]=!0,(c=a.querySelector("style"))?c.innerHTML=k+c.innerHTML:(c=e("style"),c.innerHTML=k,a.insertBefore(c,a.firstChild)));return}a.h=a.h||{};a.h[c]||(a.h[c]=!0,d=e("style"),d.dataset.cmp=c,d.innerHTML=k,a.appendChild(d))}}}}}(u,u.document,t,t.NextTickCtrl);(function(a,b,c,d,f){Object.keys(f||{}).forEach(function(e){class g extends HTMLElement {}var h=c.aa(e,f[e]);g.prototype.connectedCallback=function(){ja(c,d,b,this,h)};g.prototype.attributeChangedCallback=
function(a,b,c){b!==c&&(a=Y(a),(b=h.props[a])&&(this[a]=0===b.type?null===c||"false"===c?!1:!0:1===b.type?parseFloat(c):c))};g.prototype.disconnectedCallback=function(){if(this){var a=this.v;if(a){a.ionViewWillUnload&&a.ionViewWillUnload();var b=a.i;if(b){for(var c=Object.keys(b),e=0;e<c.length;e++)b[c[e]]();a.i=null}a.m&&N(a.m);this.v=a.$el=a.$meta=a.A=a.m=null}}};g.observedAttributes=h.K;a.customElements.define(e,g)})})(u,function(a){function b(b){return function(){a.w(a.I(b),b)}}function c(b,d,
f,m){var e=void 0,g=b.b;void 0!==g&&q(e=g.o)&&q(e=e.da)&&(e(b),g=b.b);var h=b.j,n=b.c;if("!"===n)void 0===b.f&&(b.f=""),b.a=a.O(b.f);else if(m&&"slot"===n)for(;d=m.shift();){a.w(d.parentNode,d);if(0===m.length)return d;a.u(f,d)}else if(void 0!==n){var l=n.indexOf("#");f=n.indexOf(".",l);var r=0<l?l:n.length,v=0<f?f:n.length,l=-1!==l||-1!==f?n.slice(0,Math.min(r,v)):n,g=b.a=q(g)&&q(e=g.Z)?a.R(e,l):a.P(l);r<v&&g.setAttribute("id",n.slice(r+1,v));0<f&&g.setAttribute("class",n.slice(v+1).replace(/\./g,
" "));T(I,b);V(I,b);M(I,b);X(I,b);if(h&&h.constructor===Array)for(e=0;e<h.length;++e)n=h[e],null!=n&&a.u(g,c(n,d,g,m));else J(b.f)&&a.u(g,a.G(b.f));e=b.b.o;q(e)&&(e.create&&e.create(I,b),e.ea&&d.push(b))}else b.a=a.G(b.f);return b.a}function d(c,d,f,m){for(;f<=m;++f){var e=void 0,g,h=d[f];null!=h&&(q(h.c)?(N(h),g=b(h.a),q(e=h.b)&&q(e=e.o)&&q(e=e.remove)?e(h,g):g()):a.w(c,h.a))}}function f(b,g,h,m){if(m||"slot"!==b.c){var e=void 0,w=void 0;q(e=g.b)&&q(w=e.o)&&q(e=w.ja)&&e(b,g);var p=g.a=b.a,n=b.j,
l=g.j;if(b!==g){void 0!==g.b&&(T(b,g),V(b,g),M(b,g),X(b,g),e=g.b.o,q(e)&&q(e=e.update)&&e(b,g));if(void 0===g.f)if(q(n)&&q(l)){if(n!==l){var r=m?[]:null;if(m)for(var v=g.a.childNodes,y=0;y<v.length;y++)r.push(v[y]);for(var p=p.shadowRoot||p,t=0,y=0,u=n.length-1,z=n[0],B=n[u],v=l.length-1,A=l[0],D=l[v],E=void 0,x,F;t<=u&&y<=v;)if(null==z)z=n[++t];else if(null==B)B=n[--u];else if(null==A)A=l[++y];else if(null==D)D=l[--v];else if(H(z,A))f(z,A,h,m),z=n[++t],A=l[++y];else if(H(B,D))f(B,D,h,m),B=n[--u],
D=l[--v];else if(H(z,D))f(z,D,h,m),a.g(p,z.a,a.H(B.a)),z=n[++t],D=l[--v];else{if(H(B,A))f(B,A,h,m),a.g(p,B.a,z.a),B=n[--u];else{if(void 0===E){var G;x=n;F=u;for(var C={},E=t;E<=F;++E)G=x[E],null!=G&&(G=G.s,void 0!==G&&(C[G]=E));E=C}x=E[A.s];void 0===x?a.g(p,c(A,h,p,r),z.a):(F=n[x],F.c!==A.c?a.g(p,c(A,h,p,r),z.a):(f(F,A,h,m),n[x]=void 0,a.g(p,F.a,z.a)))}A=l[++y]}if(t>u)for(m=null==l[v+1]?null:l[v+1].a,n=y;n<=v;++n)y=l[n],null!=y&&a.g(p,c(y,h,p,r),m);else y>v&&d(p,n,t,u)}}else if(q(l))for(q(b.f)&&a.B(p,
""),r=0,m=l.length-1;r<=m;++r)n=l[r],null!=n&&a.g(p,c(n,h,p,null),null);else q(n)?d(p,n,0,n.length-1):q(b.f)&&a.B(p,"");else b.f!==g.f&&a.B(p,g.f);q(w)&&q(e=w.ia)&&e(b,g)}}}return function(b,g,h){var e,k=[];void 0!==b.c||void 0!==b.a||(b=K(a.T(b)+(b.id?"#"+b.id:"")+(b.className?"."+b.className.split(" ").join("."):""),{},[],void 0,b));g.a||H(b,g)?f(b,g,k,h):(h=b.a,e=a.I(h),c(g,k,e,[]),null!==e&&(a.g(e,g.a,a.H(h)),d(e,[b],0,0)));return g}}(x),x,t.ConfigCtrl,t.components)})(window);
